### PR TITLE
Preparing for enhancements modified SDK versions in all projects.

### PR DESCRIPTION
**Pull request by vnetonline**

### CODE REVIEW

**Comment by sbwalker** [comment]
@vnetonline my apologies... I created a conflict by merging a PR for the *.sln changes (adding Oqtane.Server project)

**Comment by vnetonline** [comment]
@sbwalker I think I have fixed the merge conflict can you please merge PR?

**Comment by vnetonline** [comment]
@sbwalker, can you please merge this PR so I can submit more Enhancements as I proposed?

**Comment by sbwalker** [comment]
@vnetonline sorry for the delay... I am getting notifications from so many repos now that I miss some of them

**Pull request merged**
