### PR TITLE
Localize Oqtane.Blogs

### LINKED ISSUE #5: Localize Blogs Module
Based our discussion with @sbwalker about localization, I will start to localize the blog module this will include:

- Localize label components (If there's)

- Localize all the texts that have been rendered

- Add at least one culture, probably the default (English)

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #5

### CODE REVIEW

**Comment by hishamco** [comment]
Almost done, just need:

- Check if the `resx` file used for English culture or default culture which I think the right choice if I'm not wrong

- Localize log messages with params

**Comment by hishamco** [comment]
@sbwalker could please try this too?

**Comment by hishamco** [comment]
I test everything and LGTM just I notice unexpected bug that I will file in the Oqtane repo

**Comment by hishamco** [comment]
@sbwalker could please try this, it's pending for 4 days, if all goes well I will modify the `Module Creator` to be a localize ready

**Comment by sbwalker** [comment]
please hold off on localizing Module Creator just a bit longer

**Comment by hishamco** [comment]
> please hold off on localizing Module Creator just a bit longer

Ok

Regarding the Blogs module there's a missing piece which is the log messages which I will try to do it when I have a time

**Pull request merged**
