### PR TITLE
Upgrade to Oqtane 3.0.0 & .NET 6.0

### PR DESCRIPTION
**Pull request by hishamco**
/cc @sbwalker

### CODE REVIEW

**Comment by hishamco** [comment]
PR #17 might not be needed any more

**Comment by hishamco** [comment]
I just updated the `Oqtane.Blogs` version `2.0.0` coz the runtime version has been changed

**Comment by hishamco** [comment]
@sbwalker can we merge this?

**Comment by sbwalker** [comment]
sorry for the delay

**Comment by hishamco** [comment]
You can close #17 for now

**Pull request merged**
